backend:
  name: github
  repo: capoeiranz/capoeira.content
  branch: master
  site_domain: capoeiranz.netlify.com

media_folder: media
public_folder: /media
publish_mode: editorial_workflow
site_url: https://capoeira.org.nz

collections:
  - name: 'page'
    label: 'Page'
    folder: ''
    create: true
    extension: 'mdx'
    format: 'frontmatter'
    slug: "{{title}}"
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
