backend:
  name: git-gateway
  repo: capoeiranz/capoeira.content
  branch: master
  base_url: https://capoeiranz.netlify.app

media_folder: media
public_folder: /media
publish_mode: editorial_workflow
site_url: https://capoeira.4pi.nz

collections:
  - label: "Pages"
    name: "page"
    folder: "page"
    create: true
    extension: "mdx"
    format: "frontmatter"
    slug: "{{title}}"
    nested:
      depth: 7 # max depth to show in the collection tree
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    files:
      - label: "Grommet Theme"
        name: "grommet-theme"
        file: "settings/grommet-theme.json"
        fields:
          - label: "Code"
            name: "code"
            widget: "code"
            output_code_only: true
